name: Pipeline
run-name: Deploy by @${{ github.actor }}

on:
    push:
      branches:
        - master
    pull_request:
        branches:
            - master

jobs:
  test:
    name: Tests (Pytest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "latest"

      - name: Install dependencies
        run: poetry install --no-interaction --with dev

      - name: Run Tests (Pytest)
        run: poetry run test

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

  lint:
    name: Linting (pylint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "latest"

      - name: Install dependencies
        run: poetry install --no-interaction --with dev

      - name: Run pylint (Linting)
        run: poetry run lint

  type-check:
    name: Type Checking (Mypy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "latest"

      - name: Install dependencies
        run: poetry install --no-interaction --with dev

      - name: Run Mypy (Type Checking)
        run: poetry run typecheck
