name: Generate Notebooks
run-name: Generate Notebooks by @${{ github.actor }}

on:
  push:
    branches:
      - master

jobs:
  notebook:
      name: Generating Jupyter Notebooks
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Cache venv
          uses: actions/cache@v3
          with:
            path: ~/.cache/pypoetry
            key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

        - name: Install Poetry
          uses: abatilo/actions-poetry@v2
          with:
            poetry-version: "latest"

        - name: Install dependencies
          run: poetry install --with dev

        - name: Convert notebooks to HTML
          run: |
            for nb in notebooks/*.ipynb; do
              poetry run jupyter nbconvert --to html "$nb" --output-dir=docs/notebooks
            done

        - name: Commit and push docs
          run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add docs/
            git commit -m "docs: auto-update notebook HTMLs [skip ci]" || echo "No changes"

        - name: Push changes
          uses: ad-m/github-push-action@v0.6.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: master
